# Generated by Django 6.0.7 on 2026-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
